# Generated by Django 3.1.5 on 2021-01-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Web_Basics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
