# Generated by Django 3.1.5 on 2021-01-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Web_Basics_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
