# Generated by Django 3.1.5 on 2021-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Web_Basics_2', '0002_game_level_of_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
