# Generated by Django 3.1.5 on 2021-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Web_Basics_2', '0006_auto_20210130_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')]),
        ),
    ]
